apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: everybody
  labels:
    app: everybody
spec:
  replicas: 1
  selector:
    matchLabels:
      app: everybody
  template:
    metadata:
      labels:
        app: everybody
    spec:
      containers:
      - name: everybody
        image: us-west4-docker.pkg.dev/scum-and-villainy-bot/bots/everybody-discord-bot:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "96Mi"
            cpu: "5m"
        volumeMounts:
          - name: everybody-storage
            mountPath: /opt/storage
        envFrom:
        - secretRef:
            name: everybody-secrets
